batch_size: 64
category_counts:
- 7
- 2
- 2
device: cuda
ds_name: CSE-CIC-IDS2018
epochs: 100
exp_log_path: log\CSE-CIC-IDS2018\03-27-2025-16-39-15
exp_name: CSE-CIC-IDS2018
input_obs_loc:
- 0
known_categorical_inputs:
- 30
- 31
- 32
known_regular_inputs:
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
log_each_step: true
lr: 0.0001
model: tft
n_workers: 1
num_encoder_steps: 48
num_heads: 4
hidden_layer_size: 96
output_size: 1
quantiles:
- 0.1
- 0.5
- 0.9
seed: 5104
static_input_loc:
- 27
- 28
- 29
total_time_steps: 96
unknown_time_features:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
